# Generated by Django 2.1.5 on 2019-04-09 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inschrijven', '0004_auto_20190403_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groep', models.CharField(choices=[('L', 'Leeuwkes'), ('JK', 'Jong Knapen'), ('K', 'Knapen'), ('JH', 'Jong Hernieuwers'), ('H', 'Hernieuwers'), ('16', '+16'), ('LE', 'Leiding')], max_length=2)),
                ('beschrijving', models.TextField(max_length=1000)),
                ('groepfoto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='leiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('tel', models.IntegerField()),
                ('foto', models.FileField(upload_to='')),
                ('groepid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Groep')),
                ('lidid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
