# Generated by Django 2.1.5 on 2019-04-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groep', models.CharField(choices=[('L', 'Leeuwkes'), ('JK', 'Jong Knapen'), ('K', 'Knapen'), ('JH', 'Jong Hernieuwers'), ('H', 'Hernieuwers'), ('16', '+16'), ('LE', 'Leiding')], max_length=2)),
                ('beschrijving', models.TextField(max_length=255)),
                ('groepfoto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='leiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('tel', models.IntegerField()),
                ('foto', models.FileField(upload_to='')),
                ('groepid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Groep')),
            ],
        ),
    ]
