# Generated by Django 2.1.5 on 2019-04-09 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leiding',
            name='groepid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Groep'),
        ),
        migrations.AlterField(
            model_name='leiding',
            name='lidid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid'),
        ),
        migrations.AlterField(
            model_name='leiding',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
