# Generated by Django 2.1.5 on 2019-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumvan', models.DateTimeField()),
                ('datumtot', models.DateTimeField()),
                ('locatie', models.CharField(max_length=100)),
                ('beschrijving', models.TextField()),
            ],
        ),
    ]
