# Generated by Django 2.1.5 on 2019-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='titel',
            field=models.CharField(default='villa', max_length=100),
            preserve_default=False,
        ),
    ]
