# Generated by Django 2.1.5 on 2019-04-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendaitem_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItemBestand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.FileField(upload_to='')),
                ('agendaitemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.AgendaItem')),
            ],
        ),
    ]
