# Generated by Django 2.1.5 on 2019-04-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendaitembestand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat', models.CharField(max_length=100)),
                ('nr', models.CharField(max_length=10)),
                ('postcode', models.IntegerField(max_length=4)),
                ('stad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Adres'),
        ),
    ]
