# Generated by Django 2.1.5 on 2019-04-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190412_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='locatie',
            new_name='adres',
        ),
    ]
