# Generated by Django 2.1.5 on 2019-04-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20190412_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitembestand',
            name='agendaitemid',
        ),
        migrations.DeleteModel(
            name='AgendaItemBestand',
        ),
    ]
