# Generated by Django 2.1.5 on 2019-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
