# Generated by Django 2.1.5 on 2019-04-09 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groep', models.CharField(choices=[('L', 'Leeuwkes'), ('JK', 'Jong Knapen'), ('K', 'Knapen'), ('JH', 'Jong Hernieuwers'), ('H', 'Hernieuwers'), ('16', '+16'), ('LE', 'Leiding')], max_length=2)),
                ('beschrijving', models.TextField(max_length=255)),
                ('groepfoto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Inschrijving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('klein kamp', 'k'), ('kamp', 'K'), ('jaar', 'Y'), ('medium kamp', 'm'), ('daguitstap', 'd')], max_length=20)),
                ('beschrijving', models.TextField(max_length=200)),
                ('startdatum', models.DateTimeField()),
                ('einddatum', models.DateTimeField()),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('locatie', models.CharField(max_length=100)),
                ('actief', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('geboortedatum', models.DateField()),
                ('geslacht', models.CharField(choices=[('V', 'v'), ('M', 'm'), ('X', 'x')], max_length=1)),
                ('actief', models.BooleanField(default=True)),
                ('groepid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Groep')),
            ],
        ),
    ]
