# Generated by Django 2.1.5 on 2019-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inschrijving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('k', 'klein kamp'), ('K', 'kamp'), ('Y', 'jaar'), ('m', 'medium kamp'), ('d', 'daguitstap')], max_length=20)),
                ('beschrijving', models.TextField(max_length=200)),
                ('startdatum', models.DateTimeField()),
                ('einddatum', models.DateTimeField()),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('locatie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('geboortedatum', models.DateField()),
                ('geslacht', models.CharField(choices=[('V', 'v'), ('M', 'm'), ('X', 'x')], max_length=1)),
            ],
        ),
    ]
