# Generated by Django 2.1.5 on 2019-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijving',
            name='soort',
            field=models.CharField(choices=[('klein kamp', 'k'), ('kamp', 'K'), ('jaar', 'Y'), ('medium kamp', 'm'), ('daguitstap', 'd')], max_length=20),
        ),
    ]
