# Generated by Django 2.1.5 on 2019-04-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0002_leiding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groep',
            old_name='groep',
            new_name='naam',
        ),
    ]
