# Generated by Django 2.1.5 on 2019-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0002_auto_20190323_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschrijving',
            name='actief',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
