# Generated by Django 2.1.5 on 2019-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0004_auto_20190410_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijving',
            name='soort',
            field=models.CharField(choices=[('Klein Kamp', 'Klein Kamp'), ('Kamp', 'Kamp'), ('Jaar', 'Jaar'), ('Medium Kamp', 'Medium kamp'), ('Daguitstap', 'Daguitstap')], max_length=20),
        ),
    ]
