# Generated by Django 2.1.5 on 2019-04-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('inschrijven', '0004_auto_20190403_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='groepid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Groep'),
            preserve_default=False,
        ),
    ]
