# Generated by Django 2.1.5 on 2019-04-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendaitem_titel'),
        ('inschrijven', '0005_auto_20190411_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inschrijving',
            name='beschrijving',
        ),
        migrations.RemoveField(
            model_name='inschrijving',
            name='einddatum',
        ),
        migrations.RemoveField(
            model_name='inschrijving',
            name='locatie',
        ),
        migrations.RemoveField(
            model_name='inschrijving',
            name='soort',
        ),
        migrations.RemoveField(
            model_name='inschrijving',
            name='startdatum',
        ),
        migrations.AddField(
            model_name='inschrijving',
            name='agendaitemid',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='agenda.AgendaItem'),
            preserve_default=False,
        ),
    ]
