# Generated by Django 2.1.5 on 2019-04-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0006_auto_20190412_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='InschrijvingLid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inschrijvingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Inschrijving')),
                ('lidid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid')),
            ],
        ),
    ]
