# Generated by Django 2.1.5 on 2019-04-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190412_1735'),
        ('inschrijven', '0007_inschrijvinglid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='adresid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agenda.Adres'),
            preserve_default=False,
        ),
    ]
