# Generated by Django 2.1.5 on 2019-04-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0008_lid_adresid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschrijving',
            name='brief',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inschrijving',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
