# Generated by Django 2.1.5 on 2019-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0009_auto_20190412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groep',
            name='groepfoto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='leiding',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
