# Generated by Django 2.1.5 on 2019-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0010_auto_20190422_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groep',
            name='groepfoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inschrijving',
            name='brief',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leiding',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
