# Generated by Django 2.1.5 on 2019-04-23 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0013_auto_20190422_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Geg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50)),
                ('naam', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Ouder', 'Ouder'), ('Extra', 'Extra'), ('Huisarts', 'Huisarts')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Dieet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fiche_Geg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('allergie', models.ManyToManyField(to='inschrijven.Allergie')),
                ('dieet', models.ManyToManyField(to='inschrijven.Dieet')),
            ],
        ),
        migrations.CreateModel(
            name='Medicatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('aantal_savonds', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('hoeveelheid_savonds', models.IntegerField()),
                ('aantal_smiddags', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('hoeveelheid_smiddags', models.IntegerField()),
                ('aantal_sochtends', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0)),
                ('hoeveelheid_sochtends', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiche_geg',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid'),
        ),
        migrations.AddField(
            model_name='fiche_geg',
            name='medicatie',
            field=models.ManyToManyField(to='inschrijven.Medicatie'),
        ),
    ]
