# Generated by Django 2.1.5 on 2019-04-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0015_auto_20190427_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijvinglid',
            name='inschrijvingid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Inschrijving'),
        ),
        migrations.AlterField(
            model_name='inschrijvinglid',
            name='lidid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid'),
        ),
    ]
