# Generated by Django 2.1.5 on 2019-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0018_contact_geg_lid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche_geg',
            name='dieet',
        ),
    ]
