# Generated by Django 2.1.5 on 2019-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0019_remove_fiche_geg_dieet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dieet',
        ),
    ]
