# Generated by Django 2.1.5 on 2019-04-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0020_delete_dieet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche_geg',
            name='medicatie',
        ),
        migrations.AlterField(
            model_name='fiche_geg',
            name='allergie',
            field=models.ManyToManyField(null=True, to='inschrijven.Allergie'),
        ),
        migrations.AlterField(
            model_name='fiche_geg',
            name='lid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Lid'),
        ),
        migrations.DeleteModel(
            name='Medicatie',
        ),
    ]
