# Generated by Django 2.1.5 on 2019-05-01 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inschrijven', '0021_auto_20190430_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='InschrijvingAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groep', models.ManyToManyField(to='inschrijven.Groep')),
                ('inschrijving', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inschrijven.Inschrijving')),
            ],
        ),
        migrations.AlterField(
            model_name='fiche_geg',
            name='allergie',
            field=models.ManyToManyField(to='inschrijven.Allergie'),
        ),
    ]
