# Generated by Django 2.1.5 on 2019-04-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0007_auto_20190422_1213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.TextField(max_length=500)),
                ('prijsperpersoon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adresid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Adres')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lokaalfoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('lokaalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verhuur.Lokaal')),
            ],
        ),
        migrations.CreateModel(
            name='Materiaal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.TextField(max_length=500)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('afmeting', models.CharField(max_length=20)),
                ('beschrijving', models.TextField(max_length=500)),
                ('prijsperstuk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('tentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verhuur.Tent')),
            ],
        ),
        migrations.CreateModel(
            name='weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumvan', models.DateTimeField()),
                ('datumtot', models.DateTimeField()),
                ('groep', models.CharField(max_length=100)),
            ],
        ),
    ]
