# Generated by Django 2.1.5 on 2019-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhuur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokaal',
            name='beschrijving',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tent',
            name='beschrijving',
            field=models.TextField(max_length=1000),
        ),
    ]
