# Generated by Django 2.1.5 on 2019-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhuur', '0002_auto_20190422_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokaal',
            name='waarborg',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=5),
            preserve_default=False,
        ),
    ]
