# Generated by Django 2.1.5 on 2019-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhuur', '0004_auto_20190422_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokaalfoto',
            name='image',
            field=models.ImageField(upload_to='images/lokaal'),
        ),
        migrations.AlterField(
            model_name='tentfoto',
            name='image',
            field=models.ImageField(upload_to='images/tent'),
        ),
    ]
